apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: allegany/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
            - name: REACT_APP_URL
              value: 'https://notifyme.christoffergranstedt.com'
            - name: GITLAB_APP_ID
              value: '9d0041db3e685b41a679edb646339b7da355ebebbe59edc0e86f382c7da7f840'
            - name: GITLAB_APP_SECRET
              value: 'f2a19a4d26f28d43c5c935e2019ee8c90196a47c08677d86cd199a191b9afe69'
            - name: GITLAB_REDIRECT_URI
              value: 'https://notifyme.api.christoffergranstedt.com/api/accounts/gitlab/authenticate/callback'
            - name: SLACK_APP_ID
              value: '1753167503735.1753174200439'
            - name: SLACK_APP_SECRET
              value: '060bbf29314ed52bda0c507a5fa53328'
            - name: SLACK_REDIRECT_URI
              value: 'https://notifyme.api.christoffergranstedt.com/api/accounts/slack/authenticate/callback'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'notifyme'
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtt
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000


