apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notifyme-app
  namespace: default
spec:
  dnsNames:
    - christoffergranstedt.info
  secretName: notifyme-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
