apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services : "websocket-notification-service"
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/websocket-services: "websocket-notification-service"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  tls:
  - hosts:
    - notifyme.api.christoffergranstedt.com
    secretName: notifyme-app-tls
  rules:
    - host: notifyme.api.christoffergranstedt.com
      http:
        paths:
          - path: '/accounts/?(.*)'
            backend:
              serviceName: auth-service
              servicePort: 3000
          - path: '/groups/?(.*)'
            backend:
              serviceName: group-service
              servicePort: 3000
          - path: '/events/?(.*)'
            backend:
              serviceName: event-service
              servicePort: 3000
          - path: '/websocket/?(.*)'
            backend:
              serviceName: websocket-notification-service
              servicePort: 3000