apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-notification
  template:
    metadata:
      labels:
        app: websocket-notification
    spec:
      containers:
        - name: websocket-notification
          image: allegany/websocket-notification
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/websocket-notification'
            - name: REACT_APP_URL
              value: 'http://localhost:3000'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'notifyme'
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtt
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-notification-service
spec:
  selector:
    app: websocket-notification
  ports:
    - name: websocket-notification
      protocol: TCP
      port: 3000
      targetPort: 3000


